export const LOAD_COMMENT_LIST_STARTED = 'COMMENT/LOAD_COMMENT_LIST_STARTED';
export const LOAD_COMMENT_LIST_SUCCESS = 'COMMENT/LOAD_COMMENT_LIST_SUCCESS';
export const LOAD_COMMENT_DETAILS_STARTED = 'COMMENT/LOAD_COMMENT_DETAILS_STARTED';
export const LOAD_COMMENT_DETAILS_SUCCESS = 'COMMENT/LOAD_COMMENT_DETAILS_SUCCESS';
