export const LOAD_NUM_OF_PRODUCTS_STARTED = 'HOME/LOAD_NUM_OF_PRODUCTS_STARTED';
export const LOAD_NUM_OF_PRODUCTS_SUCCESS = 'HOME/LOAD_NUM_OF_PRODUCTS_SUCCESS';
export const LOAD_NUM_OF_COMMENTS_STARTED = 'HOME/LOAD_NUM_OF_COMMENTS_STARTED';
export const LOAD_NUM_OF_COMMENTS_SUCCESS = 'HOME/LOAD_NUM_OF_COMMENTS_SUCCESS';
export const LOAD_RECENT_ITEMS_STARTED = 'HOME/LOAD_RECENT_ITEMS_STARTED';
export const LOAD_RECENT_ITEMS_SUCCESS = 'HOME/LOAD_RECENT_ITEMS_SUCCESS';
