export const LOAD_PRODUCT_DETAILS_STARTED = 'PRODUCT/LOAD_PRODUCT_DETAILS_STARTED';
export const LOAD_PRODUCT_DETAILS_SUCCESS = 'PRODUCT/LOAD_PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_HAS_COMMENTS_STARTED = 'PRODUCT/PRODUCT_HAS_COMMENTS_STARTED';
export const PRODUCT_HAS_COMMENTS_SUCCESS = 'PRODUCT/PRODUCT_HAS_COMMENTS_SUCCESS';
